/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeMetode_BazaPodataka */

#ifndef _Included_nativeMetode_BazaPodataka
#define _Included_nativeMetode_BazaPodataka
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    addUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;DLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nativeMetode_BazaPodataka_addUser
  (JNIEnv *, jclass, jstring, jstring, jdouble, jstring);

/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    isThisTruePassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nativeMetode_BazaPodataka_isThisTruePassword
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    isThisUserNameTaken
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nativeMetode_BazaPodataka_isThisUserNameTaken
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    getBalance
 * Signature: (Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_nativeMetode_BazaPodataka_getBalance
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    setBalance
 * Signature: (Ljava/lang/String;DLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nativeMetode_BazaPodataka_setBalance
  (JNIEnv *, jclass, jstring, jdouble, jstring);

/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    dodajKupljene
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nativeMetode_BazaPodataka_dodajKupljene
  (JNIEnv *, jclass, jstring, jstring, jint, jdouble, jstring);

/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    dohvKupljene
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_nativeMetode_BazaPodataka_dohvKupljene
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    prodajAkcije
 * Signature: (Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nativeMetode_BazaPodataka_prodajAkcije
  (JNIEnv *, jclass, jstring, jint, jint, jstring);

/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    obrisiBezAkcija
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nativeMetode_BazaPodataka_obrisiBezAkcija
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    dohVKompOdId
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nativeMetode_BazaPodataka_dohVKompOdId
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     nativeMetode_BazaPodataka
 * Method:    dohvBrAkcOdId
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_nativeMetode_BazaPodataka_dohvBrAkcOdId
  (JNIEnv *, jclass, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
