/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeMetode_Parser */

#ifndef _Included_nativeMetode_Parser
#define _Included_nativeMetode_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeMetode_Parser
 * Method:    parse
 * Signature: (Ljava/lang/String;JJ)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_nativeMetode_Parser_parse
  (JNIEnv *, jclass, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
